# Generated by Django 5.0.3 on 2024-03-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_followerscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowersCount',
        ),
    ]
